// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARTYNc-zL2VZLgksWaSNnasY-LP6O9XdE',
    appId: '1:807198837601:android:66923c233866a088451320',
    messagingSenderId: '807198837601',
    projectId: 'asistencia-ie-amc',
    storageBucket: 'asistencia-ie-amc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tGVfaqJlMmlP35aE3WleQBOP30KPbs8',
    appId: '1:807198837601:ios:9506acd9d3cacee0451320',
    messagingSenderId: '807198837601',
    projectId: 'asistencia-ie-amc',
    storageBucket: 'asistencia-ie-amc.appspot.com',
    iosBundleId: 'com.unica.asistenciaieamc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf78Wn2Wnv3yB584cfaMEV1mYDKPXm894',
    appId: '1:807198837601:web:3a8e7c7cf7d38edd451320',
    messagingSenderId: '807198837601',
    projectId: 'asistencia-ie-amc',
    authDomain: 'asistencia-ie-amc.firebaseapp.com',
    storageBucket: 'asistencia-ie-amc.appspot.com',
    measurementId: 'G-KEV1GSX4RV',
  );
}
